
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;

namespace GameProto.Runtime.Config
{

    public static class Tables
    {
        public struct DataTableInfo
        {
            public Type DataRowType;
            public string DataTableName;
            public string OutputDataFile;

            public DataTableInfo(Type dataRowType, string dataTableName, string outputDataFile)
            {
                DataRowType = dataRowType;
                DataTableName = dataTableName;
                OutputDataFile = outputDataFile;
            }
        }

        public static readonly DataTableInfo[] DataTableInfos = new DataTableInfo[]
        {
            new DataTableInfo(typeof(actor.Player), "TbPlayer", "actor_tbplayer"),
            new DataTableInfo(typeof(network.Server), "TbServer", "network_tbserver"),
        };
    }

}

