
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameProto.Runtime.Config.actor
{
public sealed partial class Player : Actor
{
    /// <summary>
    /// 跑步速度（m/s）
    /// </summary>
public float RunSpeed { get; private set; }

public const int __ID__ = -872655590;

    public override bool ParseDataRow(string dataRowString, object userData)
    {
    
            if (!base.ParseDataRow(dataRowString, userData)) return false;
        
        var __node = userData as JSONNode;
        { if(!__node["run_speed"].IsNumber) { throw new SerializationException(); }  RunSpeed = __node["run_speed"]; }
        return true;
    }



    public static Player DeserializePlayer(JSONNode _buf)
    {
        return DeserializeImpl<actor.Player>();

        T DeserializeImpl<T>() where T : GameFramework.DataTable.IDataRow, new()
        {
            var inst = new T();
            if (!inst.ParseDataRow(null, _buf)) throw new SerializationException();
            return inst;
        }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "walkSpeed:" + WalkSpeed + ","
        + "runSpeed:" + RunSpeed + ","
        + "}";
    }
}
}

