
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto.Runtime.Config.world
{ 
    [System.Flags]
    public enum TileFlag
    {
        /// <summary>
        /// 可行走
        /// </summary>
        Walkable = 0,
        /// <summary>
        /// 障碍
        /// </summary>
        Obstacles = 1,
        /// <summary>
        /// 水域
        /// </summary>
        Water = 2,
    }

} 

