
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameProto.Runtime.Config.common
{
public partial struct RectInt
{
public int X { get; private set; }
public int Y { get; private set; }
public int Width { get; private set; }
public int Height { get; private set; }


    public  bool ParseDataRow(string dataRowString, object userData)
    {
    
        var __node = userData as JSONNode;
        { if(!__node["x"].IsNumber) { throw new SerializationException(); }  X = __node["x"]; }
        { if(!__node["y"].IsNumber) { throw new SerializationException(); }  Y = __node["y"]; }
        { if(!__node["width"].IsNumber) { throw new SerializationException(); }  Width = __node["width"]; }
        { if(!__node["height"].IsNumber) { throw new SerializationException(); }  Height = __node["height"]; }
        return true;
    }



    public static RectInt DeserializeRectInt(JSONNode _buf)
    {
        var inst = new RectInt();
        if (!inst.ParseDataRow(null, _buf)) throw new SerializationException();
        return inst;
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "width:" + Width + ","
        + "height:" + Height + ","
        + "}";
    }
}
}

