
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameProto.Runtime.Config.network
{ 
    /// <summary>
    /// 服务器类型
    /// </summary>
    public enum ServerType
    {
        /// <summary>
        /// 主要
        /// </summary>
        Main = 0,
        /// <summary>
        /// 资源下载
        /// </summary>
        ResourceDownload = 1,
    }

} 

